# File: lib/adk/mcp/tool_wrapper.rb
# frozen_string_literal: true

require_relative '../tool'
require_relative '../tool_registry'
require_relative 'util/schema_converter'
require_relative 'client' # Need client for execution
require_relative 'error' # Need error classes

module ADK
  module Mcp
    # Base class for dynamically created ADK::Tool wrappers around external MCP tools.
    # Instances of anonymous subclasses generated by `from_mcp_schema` are used.
    class ToolWrapper < ADK::Tool
      # General description for the base wrapper concept
      tool_description "Internal base class for dynamically wrapping external MCP tools. Instances are generated automatically."

      class << self
        # References stored on the dynamically created subclass
        attr_accessor :mcp_client, :mcp_tool_name, :mcp_input_schema
      end

      # Creates a new anonymous ADK::Tool subclass that wraps an external MCP tool.
      # Registers the new tool class with the provided ADK::ToolRegistry instance.
      #
      # @param mcp_schema [Hash] The tool schema hash from MCP server.
      # @param mcp_client [ADK::Mcp::Client] The client instance.
      # @param tool_registry [ADK::ToolRegistry] The specific registry instance to register with.
      # @return [Class] The newly created anonymous ToolWrapper subclass, or nil.
      def self.from_mcp_schema(mcp_schema, mcp_client, tool_registry)
        # Validate inputs including the registry
        unless mcp_schema.is_a?(Hash) && mcp_schema[:name] &&
               mcp_client.is_a?(ADK::Mcp::Client) &&
               tool_registry.is_a?(ADK::ToolRegistry)
          Mcp.logger.error("Invalid input for ToolWrapper.from_mcp_schema: Schema, Client, or Registry invalid.")
          return nil
        end

        mcp_name = mcp_schema[:name]
        mcp_description = mcp_schema[:description] || "MCP Tool: #{mcp_name}"
        mcp_input_schema = mcp_schema[:inputSchema] || {}
        mcp_properties = mcp_input_schema[:properties] || {}
        mcp_required = mcp_input_schema[:required] || []

        adk_params = Util::SchemaConverter.json_to_adk(mcp_properties, mcp_required)

        # Create anonymous class
        wrapper_class = Class.new(ToolWrapper) do
          # --- CAPTURE local variables for use in method definitions ---
          captured_mcp_name_sym = mcp_name.to_sym
          captured_mcp_description = mcp_description
          captured_adk_params = adk_params

          # Store references needed for execution on the class itself
          self.mcp_client = mcp_client
          self.mcp_tool_name = mcp_name # Keep original string name for execution
          self.mcp_input_schema = mcp_input_schema

          # --- Define the tool_metadata method explicitly on this anonymous class ---
          define_singleton_method(:tool_metadata) do
            {
              name: captured_mcp_name_sym,
              description: captured_mcp_description,
              parameters: captured_adk_params
            }
          end

          # --- ALSO explicitly define the individual readers for robustness ---
          # (These might be called by other parts of ADK or ToolRegistry indirectly)
          define_singleton_method(:tool_name) { captured_mcp_name_sym }
          define_singleton_method(:description) { captured_mcp_description }
          define_singleton_method(:parameters_definition) { captured_adk_params }

          # --- Keep the original define_metadata call as well for global registration ---
          # Although redundant for metadata retrieval via tool_metadata, it handles global registration.
          define_metadata(
            name: captured_mcp_name_sym,
            description: captured_mcp_description,
            parameters: captured_adk_params
          )
        end

        Mcp.logger.info("Created ADK Tool wrapper for MCP tool: '#{mcp_name}'")

        # Register with the PROVIDED registry instance
        begin
          tool_registry.register(mcp_name.to_sym, wrapper_class)
          Mcp.logger.debug("Registered wrapper for MCP tool '#{mcp_name}' with provided ToolRegistry.")
        rescue ADK::ToolRegistry::ToolExistsError => e
          Mcp.logger.warn("MCP Tool '#{mcp_name}' conflicts with an existing tool in provided registry: #{e.message}")
        rescue StandardError => e
          Mcp.logger.error("Failed to register wrapper for MCP tool '#{mcp_name}' with provided registry: #{e.message}")
          return nil
        end

        wrapper_class
      end

      # Executes the wrapped MCP tool via the stored MCP client.
      #
      # @param params [Hash] Parameters provided by the ADK agent/planner.
      # @param context [ADK::ToolContext] The execution context (less relevant for external tools).
      # @return [Hash] ADK status hash ({status: :success/:error, result:/error_message:}).
      def perform_execution(params, context)
        self.class.mcp_client || begin
          Mcp.logger.error("MCP Client not configured for tool wrapper: #{self.class.mcp_tool_name}")
          return { status: :error, error_message: "Internal configuration error: MCP Client missing." }
        end

        mcp_tool_name_str = self.class.mcp_tool_name
        mcp_client_instance = self.class.mcp_client

        Mcp.logger.info("Executing wrapped MCP tool '#{mcp_tool_name_str}' with params: #{params.inspect}")

        # TODO: V1.1 - Translate ADK params back to JSON structure based on mcp_input_schema?
        # For V1, assume flat hash structure matches between ADK and MCP tool for basic types.
        mcp_args = params.transform_keys(&:to_s) # Convert symbol keys back to strings for JSON

        begin
          result = mcp_client_instance.call_tool(mcp_tool_name_str, mcp_args)
          Mcp.logger.info("MCP tool '#{mcp_tool_name_str}' executed successfully.")
          { status: :success, result: result }
        rescue ADK::Mcp::RemoteToolError => e
          Mcp.logger.error("MCP tool '#{mcp_tool_name_str}' returned an error: #{e}")
          { status: :error, error_message: "MCP Tool Error: #{e.message}",
            error_details: { code: e.code, data: e.data } }
        rescue ADK::Mcp::ConnectionError, ADK::Mcp::ProtocolError => e
          Mcp.logger.error("MCP communication error during '#{mcp_tool_name_str}' execution: #{e.message}")
          { status: :error, error_message: "MCP Communication Error: #{e.message}" }
        rescue StandardError => e
          Mcp.logger.error("Unexpected error during MCP tool '#{mcp_tool_name_str}' execution: #{e.class} - #{e.message}")
          Mcp.logger.error(e.backtrace.join("\n"))
          { status: :error, error_message: "Internal Error: #{e.message}" }
        end
      end
    end
  end
end
